# Generated by Django 3.1 on 2020-08-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Birthday', 'Birthday'), ('Date', 'Date'), ('Anniversary', 'Anniversary')], max_length=20, null=True)),
                ('decoration_type', models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20, null=True)),
                ('decoration_cost', models.FloatField(blank=True, null=True)),
                ('decoration_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
