# Generated by Django 3.1 on 2020-08-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
    ]
