# Generated by Django 3.1 on 2020-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main Course', 'Main Course'), ('Desert', 'Desert'), ('Drinks', 'Drinks')], default='', max_length=20),
        ),
    ]
