# Generated by Django 3.1 on 2020-08-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_customer_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
