# Generated by Django 3.1 on 2020-08-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20200826_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Birthday', 'Birthday'), ('Date', 'Date'), ('Anniversary', 'Anniversary')], max_length=20, null=True)),
                ('decoration_type', models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Gold')], max_length=20, null=True)),
                ('decoration_cost', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.event'),
        ),
    ]
