# Generated by Django 3.1 on 2020-08-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('items', '0016_auto_20200826_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
