# Generated by Django 3.1 on 2020-08-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20200827_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
    ]
